// Generated by nitro
import type { Serialize, Simplify } from 'nitropack';
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    '/api/blogs': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<typeof import('../../server/api/blogs/index').default>
          >
        >
      >;
    };
    '/api/blogs/view': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<typeof import('../../server/api/blogs/view').default>
          >
        >
      >;
    };
    '/api/spotify': {
      default: Simplify<
        Serialize<
          Awaited<ReturnType<typeof import('../../server/api/spotify').default>>
        >
      >;
    };
    '/sitemap.xml': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<typeof import('../../server/routes/sitemap.xml').default>
          >
        >
      >;
    };
    '/__nuxt_error': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default
            >
          >
        >
      >;
    };
    '/api/_mdc/highlight': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxtjs/mdc/dist/runtime/shiki/event-handler').default
            >
          >
        >
      >;
    };
    '/robots.txt': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxtjs/robots/dist/runtime/server/middleware').default
            >
          >
        >
      >;
    };
    '/api/_content/query/:qid/**:params': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default
            >
          >
        >
      >;
    };
    '/api/_content/query/:qid': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default
            >
          >
        >
      >;
    };
    '/api/_content/query': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default
            >
          >
        >
      >;
    };
    '/api/_content/cache.1699238408511.json': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default
            >
          >
        >
      >;
    };
    '/api/_content/navigation/:qid/**:params': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default
            >
          >
        >
      >;
    };
    '/api/_content/navigation/:qid': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default
            >
          >
        >
      >;
    };
    '/api/_content/navigation': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default
            >
          >
        >
      >;
    };
    '/feed.atom': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt-feedme/dist/runtime/handler').default
            >
          >
        >
      >;
    };
    '/feed.xml': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt-feedme/dist/runtime/handler').default
            >
          >
        >
      >;
    };
    '/feed.json': {
      get: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/nuxt-feedme/dist/runtime/handler').default
            >
          >
        >
      >;
    };
    '/_ipx/**': {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default
            >
          >
        >
      >;
    };
  }
}
export {};
