default: plan

# run the plan
plan:
    terraform plan

# apply the plan
apply:
    terraform apply -auto-approve

# apply the plan
destroy:
    terraform destroy -auto-approve

# format files
fmt:
    terraform fmt
