title: Settings
data:
  site_name: joeymckenzie.tech
  social:
    - id: QhcJsypB
      name: Github
      url: 'https://github.com/joeymckenzie'
      icon:
        iconPrefix: lucide
        iconName: github
        iconUrl: 'https://api.iconify.design/lucide/github.svg'
        iconSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5c.08-1.25-.27-2.48-1-3.5c.28-1.15.28-2.35 0-3.5c0 0-1 0-3 1.5c-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5c-.39.49-.68 1.05-.85 1.65S8.93 17.38 9 18v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></g></svg>'
        label: 'lucide:github'
    - id: 5G3ga2Wr
      name: Twitter
      url: 'https://twitter.com/_joeyMcKenzie'
      icon:
        iconPrefix: lucide
        iconName: twitter
        iconUrl: 'https://api.iconify.design/lucide/twitter.svg'
        iconSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6c2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4c-.9-4.2 4-6.6 7-3.8c1.1 0 3-1.2 3-1.2"/></svg>'
        label: 'lucide:twitter'
    - id: mae27by2
      name: LinkedIn
      url: 'https://linkedin.com/in/joeymckenzie'
      icon:
        iconPrefix: lucide
        iconName: linkedin
        iconUrl: 'https://api.iconify.design/lucide/linkedin.svg'
        iconSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2a2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6M2 9h4v12H2z"/><circle cx="4" cy="4" r="2"/></g></svg>'
        label: 'lucide:linkedin'
    - id: VNXT3VvH
      name: Email
      url: 'mailto:joey.mckenzie.dev@gmail.com'
      icon:
        iconPrefix: lucide
        iconName: mail
        iconUrl: 'https://api.iconify.design/lucide/mail.svg'
        iconSvg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="m22 7l-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect width="20" height="16" x="2" y="4" rx="2"/></g></svg>'
        label: 'lucide:mail'
  themes:
    - light
    - dark
    - cupcake
    - bumblebee
    - emerald
    - corporate
    - synthwave
    - retro
    - cyberpunk
    - valentine
    - halloween
    - garden
    - forest
    - aqua
    - lofi
    - pastel
    - fantasy
    - wireframe
    - black
    - luxury
    - dracula
    - cmyk
    - autumn
    - business
    - acid
    - lemonade
    - night
    - coffee
    - winter
    - dim
    - nord
    - sunset
    - caramellatte
    - abyss
    - silk
