import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { getSpotifyNowPlaying } from "@/lib/spotify";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hi, I'm Joey. | joeymckenzie.tech",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const spotify = await getSpotifyNowPlaying();

  console.log("spotify", spotify);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={figtree.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto my-auto max-w-2xl px-4 lg:px-8">
            <Navbar />
            {children}
            {/* <Footer /> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
