import { Post, allPosts } from "contentlayer/generated";
import { compareDesc, format, parseISO } from "date-fns";
import Link from "next/link";

function PostCard(post: Post) {
	return (
		<div className="mb-8">
			<h2 className="mb-1 text-xl">
				<Link
					href={post.url}
					className="text-blue-700 hover:text-blue-900 dark:text-blue-400"
				>
					{post.title}
				</Link>
			</h2>
			<time
				dateTime={post.pubDate}
				className="mb-2 block text-xs text-gray-600"
			>
				{format(parseISO(post.pubDate), "LLLL d, yyyy")}
			</time>
			<div
				className="text-sm [&>*]:mb-3 [&>*:last-child]:mb-0"
				// biome-ignore lint/security/noDangerouslySetInnerHtml: generated by contentlayer
				// dangerouslySetInnerHTML={{ __html: post.body.html }}
			/>
		</div>
	);
}

export default function Home() {
	const posts = allPosts.sort((a, b) =>
		compareDesc(new Date(a.pubDate), new Date(b.pubDate)),
	);

	return (
		<div className="mx-auto max-w-xl py-8">
			<h1 className="mb-8 text-center text-2xl">
				Next.js + Contentlayer Example
			</h1>
			{posts.map((post) => (
				<PostCard key={post.url} {...post} />
			))}
		</div>
	);
}
